# Generated by Django 2.1 on 2018-11-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
